name: Merge release into main

on:
  push:
    branches:
      - release

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        source_branch: "release"
        pr_title: "Merge release into main"
        pr_body: |
          :crown: *An automated PR*

