name: Merge develop into release

on:
  push:
    - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "release"
        source_branch: "develop"
        pr_title: "Merge develop into release"
        pr_body: |
          :crown: *An automated PR*

